### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by SHXRKIEgg** [ToMe25/Better-Shields#3] opened 2021-11-17 05:36 UTC
In the Better Minecraft Modpack you can Dupe the Shields by spamming in Enchanting table. Tested standalone works fine but it seems to be a conflict with the mod [Easy Magic](https://www.curseforge.com/minecraft/mc-mods/easy-magic). Let me know if I should report this to easy magic dev instead.

https://streamable.com/hqqei6

**Comment by ToMe25** [comment] 2021-11-17 15:11
@SharkieTV Thanks for reporting This issue.

Since my mod does not modify Enchantment Table behavior in any way I don't see how this could be caused by Better Shields.
So please try whether there are other Items this also works with.

Also please add more information to both reports.
Information missing from both reports: Minecraft version(probably 1.16), both mod versions used, as well as the forge version.
Also please add the video to the Easy Magic bug report.

**Comment by Fuzss** [comment] 2021-11-17 17:46
Fixed on my end.

**Comment by ToMe25** [comment] 2021-11-17 18:55
Thanks, I'll close this then :)

**Closed as completed** 2021-11-17 18:55 UTC
